### ISSUE TITLE
Is it possible for crockford32 check symbol presence to be detected?

### ISSUE THREAD

**Issue by mofosyne** [tinychameleon/crockford32#1]
I've been reading the spec a bit and I'm a bit confused if there is a way to disambiguate between an encoded crockford32 string vs another one with a check symbol appended.

E.g. Can `91JPRV3F41BPYWKCCGGG` (no check) and `91JPRV3F41BPYWKCCGGG*` (with check) be both decoded with the check symbol automatically ignored? Given a variable length payload?

**Comment by unsrtified** [comment]
:wave: Thanks for the question.

So, the [crockford32 spec](https://www.crockford.com/base32.html) in the "Check" section states:

> The check symbol encodes the number modulo 37, ...

Since any number modulo 37 will return something in the range [0, 37), the check symbol can be any of the valid encoding symbols (the 5 special check symbols and the 32 numeric and letter symbols) . There's no effective way to determine if the last character in an encoded string is a check symbol or not, unless you artificially restrict your values so that the only check symbols generated are symbol value 32 through 36.

If you need the checksum support to detect transmission errors, my suggestion would be to always use it.
